### ISSUE TITLE
Deploy Custom Metadata Type using SFDX

### ISSUE THREAD

**Issue by ashish-garg07** [forcedotcom/sfdx-core#231]
### Summary

Try to deploy custom metadata type in scratch org to dev org. I got the issue 'Entity not found'.
When I debug the logs then found that my custom metadata is start with lower case. because of that my metadata comes in after fields on metadata.
So I think that's why I got this error because my metadata not deployed yet but trying to deploy the metadata fields.

### Steps To Reproduce:

1.  create lower case starting name of custom metadata. especially after 'f'.
1.  try to deploy it.

### Expected result

I think there is no sequence matter so it should deploy the metadata.

### Actual result

got the error.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):

**OS and version**:

**Comment by shetzel** [comment]
The issues section of this repo is only for this specific library and not the behavior of the Salesforce CLI.  Please post your CLI issue here: https://github.com/forcedotcom/cli/issues and be sure to fill out the entire issue template as incomplete reports will be closed due to a lack of information.  Thanks!
