### ISSUE TITLE
Can't name the package with first uppercase letter?

### ISSUE THREAD

**Issue by ruslan-kurchenko** [forcedotcom/sfdx-core#82]
I work on a project where we would name packages starting with uppercase letter:

```json
    "packageDirectories": [
        {
            "path": "apex/common",
            "package": "ApexCommon",
            "versionName": "Alpha - 0.1",
            "versionNumber": "0.1.0.NEXT",
            "default": true
        }
    ],
    "packageAliases": {
        "ApexCommon": "0Ho1U000000PAtVSAW",
        "ApexCommon@0.1.0-1": "04t1U000002BgRfQAK",
     }
```

The `packageAliases` node then has the list of the key with an uppercase letter at the begging.

With that, I working on the custom sfdx cli plugin and one of the commands uses `SfdxProject.resolveProjectConfig` function to parse `sfdx-project.json`.
Here is a snippet of code which causes an error when I call it: 
https://github.com/forcedotcom/sfdx-core/blob/f421eea4839eff6a8f76a4b076bfa77afc31fb17/src/sfdxProject.ts#L53-L57

It is required to enforce the rule _to avoid uppercase keys_?
Is there any workaround?
Should I try to implement a feature to omit certain keys?

**Comment by amphro** [comment]
This restriction is in place to enforce standards, which is especially useful when reading keys in code. i.e. `json.packageAliases` v.s. `json.PackageAliases`. When we didn't enforce this, it was difficult to know if a key started with upper or lower case and made the code not as clean. With that said, there is definitely a place for "user-defined" keys or "dynamic" keys that are names of things, like the keys in `packageAliases`. 

This has also been reported internally. In the salesforcedx plugin, we actually don't enforce this rule on packageAliases when we read the file, but in this library we do. I'll mark this as a bug because of that reason. We decided not to hardcode packageAliases and try to come up with another solution to whitelisting objects that contain such keys. Ideas are welcome.

To allow plugin developers the ability to do this may require some additional thought. More information on the success community. https://success.salesforce.com/0D53A00003wzhsn

**Comment by ruslan-kurchenko** [comment]
Thanks for such a quick response, @amphro!

As a workaround, I changed packages` aliases for lowercase and it is Okay for now.
I'll definitely look into Success Community, thank you!

```json
    "packageDirectories": [
        {
            "path": "apex/common",
            "package": "ApexCommon",
            "versionName": "Alpha - 0.1",
            "versionNumber": "0.1.0.NEXT",
            "default": true
        }
    ],
    "packageAliases": {
        "apexCommon": "0Ho1U000000PAtVSAW",
        "apexCommon@0.1.0-1": "04t1U000002BgRfQAK",
     }
```

**Comment by clairebianchi** [comment]
Resolved with work around.
